version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=chat-app

  app:
    build: .
    ports:
      - "5000:5000"
      - "5173:5173"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/chat-app
      - JWT_SECRET=your-secret-key-here
      - CLIENT_URL=http://localhost:5173
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mongo-data: